include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI OpenMANET Argon Theme
LUCI_DEPENDS:=+morse-mode

PKG_LICENSE:=Apache-2.0

CONFIG_LUCI_CSSTIDY:=

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
