#!/bin/sh
# Apply defaults for Morse Micro radio without overwriting existing settings

. /lib/functions.sh

fix_bcf_default() {
	local config="$1"
	config_get type "$config" type
	[ "morse" = "$type" ] || return 1

	# Determine the correct BCF file based on the board name
	# board_name is defined in /lib/functions.sh
	# You can find the board name by running `cat /tmp/sysinfo/board_name`
	board=$(board_name)
	case "$board" in
		morse,ekh01-03 |\
		morse,ekh03v3)
			bcf=bcf_mf08551.bin
		;;
		morse,ekh01v1)
			bcf=bcf_mf03120.bin
		;;
		morse,ekh01v2)
			bcf=bcf_mf08251.bin
		;;
		morse,ekh04v6)
			bcf=bcf_ekh04_v6.bin
		;;
		morse,artini)
			bcf=bcf_mm_hl1.bin
		;;
		morse,ekh01-01)
			bcf=bcf_mf15457.bin
		;;
		morse,mm6108-ekh01-sdio|\
		bcm2711,mm6108-sdio|\
		bcm2710,mm6108-sdio)
			bcf=bcf_mf04151.bin
        ;;
		morse,mm6108-ekh01-spi|\
		bcm2711,mm6108-spi|\
		bcm2710,mm6108-spi)
			bcf=bcf_fgh100mhaamd.bin
		;;
		# This is the default build target for OpenMANET
		morse,ekh01)
			bcf=bcf_fgh100mhaamd.bin
		;;
		gateworks,imx8mm-gw75xx-0x|\
		gateworks,imx8mp-gw75xx-2x)
			bcf=bcf_mf08651_us.bin
		;;
	esac

	[ -z "$bcf" ] && return 0

	uci -q set wireless."${config}".bcf="${bcf}"
	uci -q set wireless."${config}".enable_mcast_whitelist=0
	uci -q set wireless."${config}".enable_mcast_rate_control=1
	uci -q set wireless."${config}".country='US'
}

config_load wireless
config_foreach fix_bcf_default wifi-device
uci commit wireless
